version: '2.1'
jobs:
  createartifact:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "My artifact file" 
      - run: mkdir -p my_workspace
      - run: echo "Trying to write in my workspace" > my_workspace/echooutput
      - persist_to_workspace:
          root: my_workspace
          paths: 
            - echooutput
  updateartifact:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - attach_wokspace:
          at: my_workspace
      - run: |
          if [[ $( cat my_workspace/echooutput) == "Trying to write in my workspace" ]]  
            echo "It worked"
          else
            echo "Nope:" exit 1
          fi
#            >  ./artifact-1
#            mkdir /artifacts;
#            echo "My artifact file2 in a dir" > /artifacts/artifact-2;
#orbs:
#  terraform: circleci/terraform@3.2.0
workflows:
  version: '2.1'
  deploy_confluent_topics:
    jobs:
      - createartifact
      - updateartifact:
          requires:
            - createartifact